openapi: '3.0.2'
info:
  title: WASAPhoto project
  version: '0.0.1'
  description: This API allows users to upload and manage their images and informations
paths:
    /session: #doLogin
      post:
        tags: ["login"]
        summary: Logs in the user
        description: |-
          If the user does not exist, it will be created,
          and an identifier is returned.
          If the user exists, the user identifier is returned.
        operationId: doLogin
        requestBody:
          description: User details
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    example: Maria
                    pattern: 'Ë†.*?$'
                    minLength: 3
                    maxLength: 16
          required: true
        responses:
          "201":
            description: User log-in action successful
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    identifier:
                    # change here if you decide to use an integer
                    # or any other type of identifier
                      type: string
                      example: "abcdef012345"
          "400":  
            description: User log-in action failed 
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message:
                      type: string
                      description: The server cannot or will not process the request due to an apparent client error

    /users/{userID}: #setMyUserName
      parameters:
            - name: userID
              in: path
              description: Require user identification ID
              required: true
              schema: 
                type: string
      post: 
        operationId: setMyUserName
        summary: Set new username
        description: |
          Updates the exixsting resource userID.
          All userIDs must be unique.
          Setting a new userID require a already logged in user.


        requestBody:
          description: Set new username
          content: 
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    minLength: 3
                    maxLength: 16
                
        responses:
          "200":
            $ref: '#/components/responses/200'
          "400":
            $ref: '#/components/responses/400'
          "401":
            $ref: '#/components/responses/401'

    /users/{userID}/photo: 
      parameters:
          - name: userID
            in: path
            description: Require user identification code
            required: true
            schema: 
              type: string

      post: #upload photo 
        operationId: uploadPhoto
        summary: Upload a new photo 
        description: |
          Submit a new resource.
          Requires a logged in user.
        requestBody:  
          required: true
          content:
            application/json:
              schema: 
                type: object
                properties:
                    photoID:
                      type: string
                    ownerID: 
                      type: string
                    image:
                      type: string
                      format: binary
                    uploadDate:
                      type: string
                      format: time-date
                      minLength: 3
                      maxLength: 16
        responses:
          "200":
            $ref: '#/components/responses/200'
          "400":
            $ref: '#/components/responses/400'
          "401":
            $ref: '#/components/responses/401'

      delete: #deletePhoto
        operationId: deletePhoto
        summary: Delete photo
        description: |
          Delete user's photo.
          User must be logged in.
          OwnerID on the photo must match requesting user's ID.
        parameters:
          - name: photoID
            in: query
            description: Requires photo ID 
            required: true
            schema:
              type: string
        responses:
          "200":
            $ref: '#/components/responses/200'
          "400":
            $ref: '#/components/responses/400'
          "401":
            $ref: '#/components/responses/401'
    
    /photos/{photoID}/likes:
      parameters:
        - name: photoID
          in: path
          required: true
          schema:
            type: string
        - name: userID
          in: query 
          required: true
          schema:
            type: string

      post: #likePhoto
        operationId: likePhoto
        summary: Like a photo
        description: |
          Like a user photo.
          Users can like their own photos.
          If user tries to like an already liked photo the request will be accepted but not processed.
  
        responses:
          "200":
            $ref: '#/components/responses/200'
          "400":
            $ref: '#/components/responses/400'
          "401":
            $ref: '#/components/responses/401'
      delete: #unlikephoto
        
        operationId: unlikephoto
        summary: Unlike photo
        description: |
          Delete user's like to a photo.
          User must be logged in.
          To remove a like the user's ID must be in the list of likes.

        
        responses:
          "200":
            $ref: '#/components/responses/200'
          "400":
            $ref: '#/components/responses/400'
          "401":
            $ref: '#/components/responses/401'

    /photos/{photoID}/commments:      
      parameters:
      - name: photoID
        in: path
        required: true
        schema:
          type: string
      
      - name: userID
        in: query
        required: true
        schema:
          type: string
      post: #commentPhoto
        operationId: commentPhoto
        summary: Add a comment
        description: |
          Add a comment to an user photo.
          User must be logged in.
        
        responses:
          "200":
            $ref: '#/components/responses/200'
          "400":
            $ref: '#/components/responses/400'
          "401":
            $ref: '#/components/responses/401'

      delete: #uncomment photo
        operationId: uncommentPhoto
        summary: uncomment photo
        description: |
          Delete user's comment to a photo.
          User must be logged in.
          Only the Owner of a comment can remove it.
        
        responses:
          "200":
            $ref: '#/components/responses/200'
          "400":
            $ref: '#/components/responses/400'
          "401":
            $ref: '#/components/responses/401'

    /users/{userID}/followers: 

      parameters:
        - name: userID
          in: path
          required: true
          schema:
            type: string
        
        - name: username
          in: query
          required: true
          schema:
            type: string
      post:   #followUser
        
        operationId: followUser
        summary: follow another user
        description: |
          User must be logged in.
          A user can't follow another user if he is already in the follow list.
        
        
        responses:
          "200":
            $ref: '#/components/responses/200'
          "400":
            $ref: '#/components/responses/400'
          "401":
            $ref: '#/components/responses/401'

      delete: #unfollowUser
        
        operationId: unfollowUser
        summary: unfollow an user.
        description: |
          Unfollows user from follower list.
          User must be logged in.
          To unfollow user must be in follower list. 

        responses:
          "200":
            $ref: '#/components/responses/200'
          "400":
            $ref: '#/components/responses/400'
          "401":
            $ref: '#/components/responses/401'
    
    /users/{userID}/ban:
      parameters:
        - name: userID
          in: path
          required: true
          schema:
            type: string

        - name: targetID
          in: query
          required: true
          schema:
            type: string
      post: #banUser
        operationId: banUser
        summary: Ban another user
        description: |
          User must be logged in.
          A user can't ban another user if he is already in the ban list.
        
        
        responses:
          "200":
            $ref: '#/components/responses/200'
          "400":
            $ref: '#/components/responses/400'
          "401":
            $ref: '#/components/responses/401'
      delete: #unbanUser
        
        operationId: unbanUser
        summary: Unban another user
        description: |
          User must be logged in.
          To remove an user from the list he must be put in it first.
        responses:
          "200":
            $ref: '#/components/responses/200'
          "400":
            $ref: '#/components/responses/400'
          "401":
            $ref: '#/components/responses/401'
          
    /users/profile:
      parameters:
        - name: name
          in: query
          required: true
          schema:   
            type: string
      get:
        operationId: getUserProfile
        summary: get user profile
        description: |
          Allows users to fetch their profile page details and others profile page.
          It will show the user's photos, how many photos hav beenn uploaded, 
          and the user's followers and following.
        responses:
          "200":
            description: success 
            content:
              application/json:
                schema: 
                  type: object
                  properties:
                    photos: 
                      type: array
                      minItems: 0
                      maxItems: 99999
                      items: 
                        type: object
                        properties:
                          photoID:
                            type: string
                          image:
                            type: string
                            format: binary
                            minLength: 3
                            maxLength: 16
                          uploadDate:
                            type: string
                            format: time-date
                            minLength: 3
                            maxLength: 16
                    upNum:
                      type: integer
                    follower: 
                      type: array
                      minItems: 0
                      maxItems: 99999
                      items:
                        type: object
                        properties:
                          username:   
                            type: string

                    following: 
                      type: array
                      minItems: 0
                      maxItems: 99999
                      items:
                        type: object
                        properties:
                          username:   
                            type: string
          "400":
              $ref: '#/components/responses/400'
          "401":
              $ref: '#/components/responses/401'                 
                 
    /users/{userID}/stream: #getMyStream
      parameters:
        - name: userID
          in: path
          required: true
          schema: 
            type: string
            
      get:
        operationId: getMyStream
        summary: Present stream of photos
        description: |
          user will be presented with a stream of photos (images) in reverse chronological order, with
          information about when each photo was uploaded (date and time) and how many likes and comments
          it has.
        responses:
          "200":
            description: success
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    photos: 
                      type: array
                      minItems: 0
                      maxItems: 99999
                      items:
                        type: object
                        properties:
                          photoID:
                            type: integer
                          image:
                            type: string
                            format: binary
                          uploadDate:
                            type: string
                            format: time-date
                          likes:
                            type: integer
                          comments: 
                            type: integer
          "400":
              $ref: '#/components/responses/400'
          "401":
              $ref: '#/components/responses/401'                  
                        

components:
  securitySchemes:
    bearerAuth:            
      type: http
      scheme: bearer
      bearerFormat: JWT 
  
  responses:
    
    '200':
      description: Success
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                  description: New username set successfully


    '400':
      description: Bad Request
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                  description: The server cannot or will not process the request due to an apparent client error
    '401':
          description: Unauthorized Access
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message:
                      type: string
                      description: Access token is missing or invalid 
security: #apply the security globally to all operations
  - bearerAuth: []  